import React from 'react';

export default function EconomicsSection() {
  return (
    <section id="economics" className="section-dark section-grid-bg">
      <div className="container">
        <div className="section-header reveal">
          <span className="label">Fiscal Projections</span>
          <h2>Economic <em className="serif text-blue-light">Impact Model</em></h2>
          <p>Conservative 10-year projections with a 30% annual growth cap.</p>
        </div>
        <div className="economics-grid reveal">
          <div className="econ-stat">
            <div className="econ-value">$73M+</div>
            <div className="econ-label">Direct Gov Revenue</div>
          </div>
          <div className="econ-stat">
            <div className="econ-value">$298M+</div>
            <div className="econ-label">Total Ecosystem</div>
          </div>
          <div className="econ-stat">
            <div className="econ-value">$0</div>
            <div className="econ-label">Gov Capital Outlay</div>
          </div>
          <div className="econ-stat">
            <div className="econ-value">30%</div>
            <div className="econ-label">Annual Growth Cap</div>
          </div>
        </div>
        <p className="econ-note reveal">
          The Government of Montserrat receives direct revenue per applicant, with additional economic stimulus from business registrations, financial services, and broader ecosystem activity generated by the programme.
        </p>
      </div>
    </section>
  );
}
