/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FCDIDRegistry__factory } from "./FCDIDRegistry__factory";
export { ZkPVerifier__factory } from "./ZkPVerifier__factory";
