/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  ZkPVerifier,
  ZkPVerifierInterface,
} from "../../contracts/ZkPVerifier";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "publicInputHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    name: "ProofVerified",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "proof",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "publicInputHash",
        type: "bytes32",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "isValid",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b506102d78061001d5f395ff3fe608060405234801561000f575f80fd5b5060043610610029575f3560e01c80631858cb5b1461002d575b5f80fd5b61004760048036038101906100429190610199565b61005d565b6040516100549190610210565b60405180910390f35b5f8084849050116100a3576040517f08c379a000000000000000000000000000000000000000000000000000000000815260040161009a90610283565b60405180910390fd5b60019050813373ffffffffffffffffffffffffffffffffffffffff167fe8ad06fecfe3c13cc84998449b1933654518c4ba62322f6f5f079ca0e8e82233836040516100ee9190610210565b60405180910390a39392505050565b5f80fd5b5f80fd5b5f80fd5b5f80fd5b5f80fd5b5f8083601f84011261012657610125610105565b5b8235905067ffffffffffffffff81111561014357610142610109565b5b60208301915083600182028301111561015f5761015e61010d565b5b9250929050565b5f819050919050565b61017881610166565b8114610182575f80fd5b50565b5f813590506101938161016f565b92915050565b5f805f604084860312156101b0576101af6100fd565b5b5f84013567ffffffffffffffff8111156101cd576101cc610101565b5b6101d986828701610111565b935093505060206101ec86828701610185565b9150509250925092565b5f8115159050919050565b61020a816101f6565b82525050565b5f6020820190506102235f830184610201565b92915050565b5f82825260208201905092915050565b7f50726f6f662063616e6e6f7420626520656d70747900000000000000000000005f82015250565b5f61026d601583610229565b915061027882610239565b602082019050919050565b5f6020820190508181035f83015261029a81610261565b905091905056fea2646970667358221220ee6981ab31def446c2b71392eeb0b7d17d66dfff84280e42d91b8d369255c79b64736f6c63430008180033";

type ZkPVerifierConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ZkPVerifierConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ZkPVerifier__factory extends ContractFactory {
  constructor(...args: ZkPVerifierConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ZkPVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ZkPVerifier__factory {
    return super.connect(runner) as ZkPVerifier__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ZkPVerifierInterface {
    return new Interface(_abi) as ZkPVerifierInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ZkPVerifier {
    return new Contract(address, _abi, runner) as unknown as ZkPVerifier;
  }
}
